### PR TITLE
fix for issue #2

### PR DESCRIPTION
**Pull request by rikribbers**
I ran into an issue with the conversion as described in #2 and fixed is

### CODE REVIEW

**Comment by Nr18** [comment]
@rikribbers your pull requests fails to build do you see any change to have a look at it, i tried but java isn't my thing.

**Comment by rikribbers** [comment]
Did a quick check, looks like a problem with converting time in seconds to time in milliseconds. Will have to dig a little deeper into this. Will do that when I can find the time for it.

**Comment by Nr18** [comment]
That would be great!

**Comment by rikribbers** [comment]
not completely sure if it correct though... 

timeSpentInMillis=0.004  

should this be an integer? (4 ms instead of 0.004 seconds)

**Pull request merged**
